name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on push to main branch
  pull_request:
    branches:
      - main  # Trigger pipeline on pull requests to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Docker using Docker's convenience script
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t your-docker-image-tag .

      # Authenticate with Docker Hub or another registry if needed
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image to Docker Hub or another registry
      - name: Push Docker image
        run: |
          docker tag your-docker-image-tag your-docker-registry/your-docker-image-tag:latest
          docker push your-docker-registry/your-docker-image-tag:latest

